services:
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service-app
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_8GCgHpKT4Lsm@ep-wild-pond-am4rt4w9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
    ports:
      - "3001:3001"
    restart: always

  data-siswa-service:
    build: 
      context: ./data-siswa-service
      dockerfile: Dockerfile
    container_name: data-siswa-service-app
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_8GCgHpKT4Lsm@ep-wild-pond-am4rt4w9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
    ports:
      - "3002:3002"
    restart: always

  absensi-service:
    build: 
      context: ./absensi-service
      dockerfile: Dockerfile
    container_name: absensi-service-app
    env_file: ./absensi-service/.env
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_8GCgHpKT4Lsm@ep-wild-pond-am4rt4w9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
    ports:
      - "3003:3003"
    restart: always

  data-guru-service:
    build: 
      context: ./data-guru-service
      dockerfile: Dockerfile
    container_name: data-guru-service-app
    env_file: ./data-guru-service/.env
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_8GCgHpKT4Lsm@ep-wild-pond-am4rt4w9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
    ports:
      - "3004:3000"
    restart: always
